#!/usr/bin/env php
<?php
/**
 * PHPSword命令行入口文件
 * 启动服务：php sword server start
 * 常驻内存：php sword server start -d
 * 停止服务：php sword server stop
 * 更多详细文档介绍，请转到：
 * https://github.com/php-sword/sword
 */

$file = __DIR__ . '/vendor/autoload.php';

if(file_exists($file)) {
    require $file;
}else{
    die("include composer autoload.php fail\n Please run: composer install\n");
}

defined('ROOT_PATH') or define('ROOT_PATH', __DIR__);

\Sword\SwordEvent::bootstrap($argv);
